repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        files: ^.*.py$
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: ruff-format
        files: ^.*.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    # Mypy version.
    rev: v1.10.1 # Can likely upgrade this now
    hooks:
      - id: mypy
        name: mypy
        language: system
        files: ^.*.py$
        entry: /bin/bash -c "uv sync --frozen --extra dev && uv run mypy tlm/ tests/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=700000"]
      - id: check-toml
      - id: check-yaml
